@startuml
skinparam componentStyle rectangle
skinparam backgroundColor white
skinparam defaultTextAlignment center

skinparam component {
  BackgroundColor #FFFEF0
  BorderColor #888888
  FontSize 13
  FontStyle bold
  ArrowColor #555555
}

skinparam interface {
  BackgroundColor white
  BorderColor #555555
}

skinparam arrow {
  Color #555555
  FontSize 11
}

title Exercise 6.3 - Wellness Microservices Architecture

' Subsistemas
package "«subsystem» Client" {
  component ":WellnessClient\n(menu 18 opciones)" as Client
}

package "«subsystem» AppointmentService" {
  component ":AppointmentServiceImpl\n(5 RPCs)" as AppSvc
  database ":Appointments Map" as AppDb
}

package "«subsystem» MedicalService" {
  component ":MedicalServiceImpl\n(4 RPCs)" as MedSvc
  database ":Specialties Map" as MedDb
}

package "«subsystem» GymService" {
  component ":GymServiceImpl\n(4 RPCs)" as GymSvc
  database ":Sessions Map" as GymDb
}

package "«subsystem» RecreationService" {
  component ":RecreationServiceImpl\n(4 RPCs)" as RecSvc
  database ":Resources Map" as RecDb
}

' Provided interfaces
interface "gRPC :50061\nAppointmentService" as IApp
interface "gRPC :50062\nMedicalService" as IMed
interface "gRPC :50063\nGymService" as IGym
interface "gRPC :50064\nRecreationService" as IRec

' Conexiones (ball = provee, socket = requiere)
' Microservicios proveen gRPC
AppSvc --( IApp
MedSvc --( IMed
GymSvc --( IGym
RecSvc --( IRec

' Cliente requiere los 4 servicios
Client -- IApp
Client -- IMed
Client -- IGym
Client -- IRec

' Servidores usan sus BD
AppSvc --> AppDb : <<use>>
MedSvc --> MedDb : <<use>>
GymSvc --> GymDb : <<use>>
RecSvc --> RecDb : <<use>>

@enduml
