@startuml
skinparam componentStyle rectangle
skinparam backgroundColor white
skinparam defaultTextAlignment center

skinparam component {
  BackgroundColor #FFFEF0
  BorderColor #888888
  FontSize 13
  FontStyle bold
  ArrowColor #555555
}

skinparam interface {
  BackgroundColor white
  BorderColor #555555
}

skinparam arrow {
  Color #555555
  FontSize 11
}

title Guide 2.2 - MovieServer TCP Architecture

' Subsistemas
package "«subsystem» Client" {
  component ":MovieClient" as MovieClient
}

package "«subsystem» MovieServer" {
  component ":MovieServer" as MovieServer
  component ":MovieRepository" as MovieRepo
  component ":Movie" as MovieModel
}

' Provided interfaces
interface "TCP :35000" as ITcp

' Conexiones (ball = provee, socket = requiere)
' MovieServer provee TCP socket
MovieServer --( ITcp

' MovieClient requiere TCP
MovieClient -- ITcp

' MovieServer usa repositorio
MovieServer --> MovieRepo : <<use>>

' Repositorio contiene modelo
MovieRepo --> MovieModel : <<use>>

@enduml
