@startuml
skinparam componentStyle rectangle
skinparam backgroundColor white
skinparam defaultTextAlignment center

skinparam component {
  BackgroundColor #FFFEF0
  BorderColor #888888
  FontSize 13
  FontStyle bold
  ArrowColor #555555
}

skinparam interface {
  BackgroundColor white
  BorderColor #555555
}

skinparam arrow {
  Color #555555
  FontSize 11
}

title Guide 6.2 - Movie Microservices Architecture

' Subsistemas
package "«subsystem» Client" {
  component ":MicroserviceClient\n(menu 5 opciones)" as Client
}

package "«subsystem» MovieService" {
  component ":MovieServiceImpl" as MovieSvc
  database ":Movies Map" as MovieDb
}

package "«subsystem» ReviewService" {
  component ":ReviewServiceImpl" as ReviewSvc
  database ":Reviews Map" as ReviewDb
}

package "«subsystem» RecommendationService" {
  component ":RecommendationServiceImpl" as RecSvc
  database ":Recommendations\nMap" as RecDb
}

' Provided interfaces
interface "gRPC :50051\nMovieService" as IMovie
interface "gRPC :50052\nReviewService" as IReview
interface "gRPC :50053\nRecommendationService" as IRec

' Conexiones (ball = provee, socket = requiere)
' Microservicios proveen gRPC
MovieSvc --( IMovie
ReviewSvc --( IReview
RecSvc --( IRec

' Cliente requiere los 3 servicios
Client -- IMovie
Client -- IReview
Client -- IRec

' Servidores usan sus BD
MovieSvc --> MovieDb : <<use>>
ReviewSvc --> ReviewDb : <<use>>
RecSvc --> RecDb : <<use>>

@enduml
